export type RecipeFamily = "Reversal" | "Momentum" | "Volatility & risk" | "Volume & liquidity" | "Intraday & gaps" | "WorldQuant 101" | "Fundamentals" | "Blends";

export interface Recipe {
  id: string;
  name: string;
  family: RecipeFamily;
  /** 1 = starter, 2 = intermediate, 3 = advanced */
  level: 1 | 2 | 3;
  /** The hypothesis in plain English */
  idea: string;
  expression: string;
  /** Where the idea comes from, when it has a known origin */
  source?: string;
  /** One or two ways to vary it */
  tweaks: string[];
}

export const RECIPE_FAMILIES: RecipeFamily[] = ["Reversal", "Momentum", "Volatility & risk", "Volume & liquidity", "Intraday & gaps", "WorldQuant 101", "Fundamentals", "Blends"];

export const RECIPES: Recipe[] = [
  // ── Reversal ────────────────────────────────────────────────────────────────
  {
    id: "reversal-1d",
    name: "1-day reversal",
    family: "Reversal",
    level: 1,
    idea: "Yesterday's biggest losers tend to bounce and its biggest winners tend to give some back. The simplest and fastest reversal.",
    expression: "rank(-returns)",
    source: "Lehmann (1990); Jegadeesh (1990)",
    tweaks: ["Look further back: rank(-ts_delta(close, 5))", "Smooth it to trade less: rank(-ts_decay_linear(returns, 3))"],
  },
  {
    id: "reversal-5d",
    name: "Weekly reversal",
    family: "Reversal",
    level: 1,
    idea: "Fade the past week's move. Stocks that fell over five days tend to recover; stocks that jumped tend to fade.",
    expression: "rank(-ts_delta(close, 5))",
    source: "Lehmann (1990)",
    tweaks: ["Change the 5 to 3 or 10", "Remove the sector effect: wrap it in group_neutralize(…, sector)"],
  },
  {
    id: "reversal-21d",
    name: "Monthly reversal",
    family: "Reversal",
    level: 1,
    idea: "The same idea over a month. Slower and cheaper to trade, because the ranking changes less each day.",
    expression: "rank(-ts_delta(close, 21))",
    source: "Jegadeesh (1990)",
    tweaks: ["Compare 10, 21 and 42 days", "Skip the most recent week: rank(-(ts_delay(close, 5) / ts_delay(close, 26) - 1))"],
  },
  {
    id: "reversal-decay",
    name: "Decayed reversal",
    family: "Reversal",
    level: 2,
    idea: "Fade recent returns, but weight yesterday more than last week. The decay smooths the signal and cuts turnover.",
    expression: "rank(-ts_decay_linear(returns, 5))",
    tweaks: ["Try a window of 3 or 10", "Wrap in group_neutralize(…, sector)"],
  },
  {
    id: "reversal-sector",
    name: "Sector-neutral reversal",
    family: "Reversal",
    level: 2,
    idea: "Fade yesterday's move after removing what the whole sector did, so you bet on stock-specific overreaction and not on sectors.",
    expression: "group_neutralize(rank(-returns), sector)",
    tweaks: ["Use a 5-day move instead of 1", "Compare with and without the neutralization"],
  },
  {
    id: "ma-gap",
    name: "Stretch from the moving average",
    family: "Reversal",
    level: 2,
    idea: "When a stock is far above its own 20-day average, bet on a pullback. When it's far below, bet on a bounce.",
    expression: "rank(-(close / ts_mean(close, 20) - 1))",
    tweaks: ["Try 10 or 50 days for the average", "Divide by ts_std(close, 20) to measure stretch in volatility units"],
  },
  {
    id: "price-zscore",
    name: "Price z-score",
    family: "Reversal",
    level: 2,
    idea: "A Bollinger-band style signal: how many standard deviations is the price from its recent average? Bet that extremes revert.",
    expression: "rank(-(close - ts_mean(close, 20)) / ts_std(close, 20))",
    tweaks: ["Change the 20 in both places together", "Use returns in place of close"],
  },

  // ── Momentum ────────────────────────────────────────────────────────────────
  {
    id: "momentum-12-1",
    name: "12-1 momentum",
    family: "Momentum",
    level: 2,
    idea: "Back the past year's winners, but skip the most recent month, which tends to reverse. The classic academic momentum factor.",
    expression: "rank(ts_delay(close, 21) / ts_delay(close, 252) - 1)",
    source: "Jegadeesh & Titman (1993)",
    tweaks: ["Needs a year of history, so the first year of any test is empty", "Try 126 days instead of 252"],
  },
  {
    id: "momentum-63d",
    name: "Quarterly momentum",
    family: "Momentum",
    level: 1,
    idea: "Back the stocks that rose most over the past three months.",
    expression: "rank(ts_delta(close, 63) / ts_delay(close, 63))",
    source: "Jegadeesh & Titman (1993)",
    tweaks: ["Neutralize by sector with group_neutralize(…, sector)", "Compare 21, 63 and 126 days"],
  },
  {
    id: "high-52w",
    name: "Near the 52-week high",
    family: "Momentum",
    level: 2,
    idea: "Stocks trading close to their 52-week high tend to keep rising, because investors anchor on that high and under-react to good news.",
    expression: "rank(close / ts_max(close, 252))",
    source: "George & Hwang (2004)",
    tweaks: ["Try ts_max over 126 days", "Combine with low volatility using rank() + rank()"],
  },
  {
    id: "trend-efficiency",
    name: "Efficient trends",
    family: "Momentum",
    level: 3,
    idea: "Prefer stocks whose gains came in a straight line, not a choppy zigzag. Net change divided by total movement.",
    expression: "rank(ts_delta(close, 20) / ts_sum(abs(ts_delta(close, 1)), 20))",
    source: "Kaufman's efficiency ratio",
    tweaks: ["Change both 20s together", "Use the negative to bet that smooth trends reverse"],
  },
  {
    id: "range-position",
    name: "Position in the 60-day range",
    family: "Momentum",
    level: 1,
    idea: "Stocks near the top of their own last 60 days keep going; stocks near the bottom keep sinking.",
    expression: "rank(ts_rank(close, 60))",
    tweaks: ["Try 20 or 120 days", "Flip the sign and compare"],
  },

  // ── Volatility & risk ───────────────────────────────────────────────────────
  {
    id: "low-vol-60",
    name: "Low volatility",
    family: "Volatility & risk",
    level: 1,
    idea: "Calm stocks have historically earned as much as jumpy ones with far less risk, so the market seems to overpay for excitement.",
    expression: "rank(-ts_std(returns, 60))",
    source: "Ang, Hodrick, Xing & Zhang (2006); Blitz & van Vliet (2007)",
    tweaks: ["Try 20 or 120 days", "Neutralize by sector"],
  },
  {
    id: "low-vol-20",
    name: "Low volatility (1 month)",
    family: "Volatility & risk",
    level: 1,
    idea: "The same calm-stocks idea over a shorter window, so it reacts faster.",
    expression: "rank(-ts_std(returns, 20))",
    source: "Ang, Hodrick, Xing & Zhang (2006)",
    tweaks: ["Compare with the 60-day version", "Use ts_std(close, 20) / ts_mean(close, 20) for a price-scaled version"],
  },
  {
    id: "max-effect",
    name: "Avoid lottery tickets (MAX)",
    family: "Volatility & risk",
    level: 2,
    idea: "Stocks that had one huge up day recently attract gamblers and tend to underperform afterwards.",
    expression: "rank(-ts_max(returns, 21))",
    source: "Bali, Cakici & Whitelaw (2011)",
    tweaks: ["Average the top few days instead of just the single best", "Try a 63-day window"],
  },
  {
    id: "narrow-range",
    name: "Quiet trading ranges",
    family: "Volatility & risk",
    level: 2,
    idea: "Stocks whose daily high-to-low range has been narrow tend to be steadier and earn more per unit of risk.",
    expression: "rank(-ts_mean(range, 20))",
    tweaks: ["Try 5 or 60 days", "Blend with low volatility using rank() + rank()"],
  },

  // ── Volume & liquidity ──────────────────────────────────────────────────────
  {
    id: "price-volume-corr",
    name: "Price-volume divergence",
    family: "Volume & liquidity",
    level: 2,
    idea: "When price and volume rise together the move is crowded and tends to fade. Bet against stocks where they are tightly correlated.",
    expression: "rank(-ts_corr(close, volume, 10))",
    tweaks: ["Try 5 or 20 days", "Use returns in place of close"],
  },
  {
    id: "volume-surge",
    name: "Attention (volume surge)",
    family: "Volume & liquidity",
    level: 2,
    idea: "Stocks trading far more than usual are getting attention, and attention has historically been followed by higher returns.",
    expression: "rank(ts_mean(volume, 5) / ts_mean(volume, 60))",
    source: "Gervais, Kaniel & Mingelgrin (2001)",
    tweaks: ["Try 10 vs 120 days", "Combine with a reversal signal"],
  },
  {
    id: "amihud",
    name: "Illiquidity premium",
    family: "Volume & liquidity",
    level: 3,
    idea: "Stocks whose prices move a lot per dollar traded are costly to trade, and investors demand extra return for holding them.",
    expression: "rank(ts_mean(abs(returns) / cap, 21))",
    source: "Amihud (2002)",
    tweaks: ["Here cap is dollar volume (price × volume)", "Try a 63-day average"],
  },
  {
    id: "low-volume",
    name: "Quiet stocks",
    family: "Volume & liquidity",
    level: 1,
    idea: "Stocks trading below their usual volume are overlooked. Bet on the overlooked.",
    expression: "rank(-volume_ratio)",
    tweaks: ["Replace volume_ratio with ts_mean(volume, 5) / ts_mean(volume, 60)", "Neutralize by sector"],
  },

  // ── Intraday & gaps ─────────────────────────────────────────────────────────
  {
    id: "gap-fade",
    name: "Overnight gap fade",
    family: "Intraday & gaps",
    level: 1,
    idea: "Stocks that gap up at the open tend to drift back down during the day, and gap-downs tend to recover.",
    expression: "rank(-gap)",
    source: "Related: Lou, Polk & Skouras (2019)",
    tweaks: ["Smooth over 3 days with ts_mean(gap, 3)", "Neutralize by sector"],
  },
  {
    id: "intraday-fade",
    name: "Intraday fade",
    family: "Intraday & gaps",
    level: 1,
    idea: "Bet against what happened between the open and the close: stocks that rose all day give some back, and the reverse.",
    expression: "rank(open - close)",
    tweaks: ["Scale by the day's range: (open - close) / (high - low)", "Average over 3 days"],
  },
  {
    id: "close-location",
    name: "Where the day closed",
    family: "Intraday & gaps",
    level: 2,
    idea: "A close near the day's low often marks selling exhaustion and a bounce, while a close at the high often marks a fade.",
    expression: "rank(-(close - low) / (high - low))",
    tweaks: ["Average over 3 days: ts_mean(…, 3)", "Remove the minus sign and compare"],
  },
  {
    id: "close-vs-vwap",
    name: "Close versus average price",
    family: "Intraday & gaps",
    level: 1,
    idea: "A stock that closes below the day's average trade price has been sold into the close and tends to bounce.",
    expression: "rank(vwap - close)",
    tweaks: ["Note: vwap here is approximated as (high + low + close) / 3", "Divide by close to make it a percentage"],
  },

  // ── WorldQuant 101 ──────────────────────────────────────────────────────────
  {
    id: "wq-101",
    name: "Alpha#101",
    family: "WorldQuant 101",
    level: 2,
    idea: "How far the day closed above its open, as a share of the day's range. The 0.001 stops a divide-by-zero on flat days.",
    expression: "(close - open) / ((high - low) + 0.001)",
    source: "Kakushadze (2016), \"101 Formulaic Alphas\"",
    tweaks: ["Put rank() around it", "Flip the sign and compare"],
  },
  {
    id: "wq-6",
    name: "Alpha#6",
    family: "WorldQuant 101",
    level: 2,
    idea: "Over 10 days, how closely did the open price track volume? Bet against stocks where they moved together.",
    expression: "-1 * ts_corr(open, volume, 10)",
    source: "Kakushadze (2016), \"101 Formulaic Alphas\"",
    tweaks: ["Try 5 or 20 days", "Wrap in rank()"],
  },
  {
    id: "wq-12",
    name: "Alpha#12",
    family: "WorldQuant 101",
    level: 3,
    idea: "If volume rose, bet against today's price move; if volume fell, bet with it. Direction comes from volume, size from price.",
    expression: "sign(ts_delta(volume, 1)) * (-1 * ts_delta(close, 1))",
    source: "Kakushadze (2016), \"101 Formulaic Alphas\"",
    tweaks: ["Wrap in rank()", "Use a 3-day delta"],
  },
  {
    id: "wq-33",
    name: "Alpha#33",
    family: "WorldQuant 101",
    level: 2,
    idea: "Compares the open to the close as a ratio, then ranks it. Bet on stocks that closed well above their open.",
    expression: "rank(-1 * (1 - (open / close)))",
    source: "Kakushadze (2016), \"101 Formulaic Alphas\"",
    tweaks: ["Compare with rank(open - close)", "Neutralize by sector"],
  },
  {
    id: "wq-41",
    name: "Alpha#41",
    family: "WorldQuant 101",
    level: 2,
    idea: "The midpoint of the day's high and low versus the average trade price: where did the day's action really happen?",
    expression: "power(high * low, 0.5) - vwap",
    source: "Kakushadze (2016), \"101 Formulaic Alphas\"",
    tweaks: ["Divide by close to scale it", "Wrap in rank()"],
  },
  {
    id: "wq-3",
    name: "Alpha#3",
    family: "WorldQuant 101",
    level: 3,
    idea: "Like Alpha#6, but each side is ranked across stocks before the correlation, so outliers don't dominate.",
    expression: "-1 * ts_corr(rank(open), rank(volume), 10)",
    source: "Kakushadze (2016), \"101 Formulaic Alphas\"",
    tweaks: ["Try 5 or 15 days", "Compare with Alpha#6"],
  },
  {
    id: "wq-4",
    name: "Alpha#4",
    family: "WorldQuant 101",
    level: 3,
    idea: "Rank the low across stocks, then see where today's rank sits within the past 9 days. Bet against stocks climbing that ladder.",
    expression: "-1 * ts_rank(rank(low), 9)",
    source: "Kakushadze (2016), \"101 Formulaic Alphas\"",
    tweaks: ["Try 5 or 15 days", "Use rank(close) in place of rank(low)"],
  },
  {
    id: "wq-54",
    name: "Alpha#54",
    family: "WorldQuant 101",
    level: 3,
    idea: "A ratio built from the day's open, high, low and close, tilted by how far each sits from the other. Shows how these alphas get intricate.",
    expression: "(-1 * ((low - close) * power(open, 5))) / ((low - high) * power(close, 5))",
    source: "Kakushadze (2016), \"101 Formulaic Alphas\"",
    tweaks: ["Wrap in rank()", "Try power(…, 3) instead of 5"],
  },

  // ── Fundamentals ────────────────────────────────────────────────────────────
  {
    id: "value-bm",
    name: "Book-to-market value",
    family: "Fundamentals",
    level: 1,
    idea: "Cheap stocks (high book value relative to price) have historically beaten expensive ones. The classic value factor. It moves slowly, so it barely trades.",
    expression: "rank(book_to_market)",
    source: "Fama & French (1992)",
    tweaks: ["Use group_neutralize(\u2026, sector) so you're not just buying banks", "Compare with earnings_yield"],
  },
  {
    id: "value-ey",
    name: "Earnings yield",
    family: "Fundamentals",
    level: 1,
    idea: "Earnings divided by price, the inverse of P/E. Buy stocks that earn a lot per dollar you pay for them.",
    expression: "rank(earnings_yield)",
    source: "Basu (1977)",
    tweaks: ["Try cashflow_yield, which is harder to manipulate than earnings", "Neutralize by sector"],
  },
  {
    id: "value-cf",
    name: "Cash-flow yield",
    family: "Fundamentals",
    level: 1,
    idea: "Operating cash flow divided by market cap. Like earnings yield, but cash is harder for a company to dress up than accounting profit.",
    expression: "rank(cashflow_yield)",
    source: "Lakonishok, Shleifer & Vishny (1994)",
    tweaks: ["Blend with earnings_yield", "Compare against sales_to_price"],
  },
  {
    id: "value-sp",
    name: "Sales-to-price",
    family: "Fundamentals",
    level: 1,
    idea: "Revenue per dollar of market cap. Works for companies with no profit yet, where earnings yield is meaningless.",
    expression: "rank(sales_to_price)",
    tweaks: ["Sector-neutralize it, since margins differ widely by sector", "Blend with earnings_yield"],
  },
  {
    id: "quality-roe",
    name: "Return on equity",
    family: "Fundamentals",
    level: 1,
    idea: "Profitable companies earn more per dollar of shareholder money. The bet is that high-quality businesses are underpriced.",
    expression: "rank(roe)",
    source: "Novy-Marx (2013), related",
    tweaks: ["Compare with roa, which ignores how much debt is used", "Check it isn't just the high-leverage stocks"],
  },
  {
    id: "quality-lev",
    name: "Low leverage",
    family: "Fundamentals",
    level: 1,
    idea: "Companies with less debt relative to assets are safer in downturns. Flip the sign to bet on the heavily indebted instead.",
    expression: "rank(-leverage)",
    source: "Asness, Frazzini & Pedersen (2019), related",
    tweaks: ["Try bet-with instead of against and see which direction held in this sample", "Blend with roe"],
  },
  {
    id: "growth-sales",
    name: "Sales growth",
    family: "Fundamentals",
    level: 2,
    idea: "Revenue now versus a year ago. Because fundamentals only change when a filing comes out, ts_delay(sales, 252) is the figure from about a year earlier.",
    expression: "rank(sales / ts_delay(sales, 252) - 1)",
    tweaks: ["Try earnings growth with net_income", "Subtract a sector average with group_neutralize"],
  },
  {
    id: "value-sector",
    name: "Value within sector",
    family: "Fundamentals",
    level: 2,
    idea: "Earnings yield, compared only against stocks in the same sector. Different sectors trade at structurally different valuations, so this asks 'cheap for its sector' instead.",
    expression: "group_neutralize(rank(earnings_yield), sector)",
    tweaks: ["Swap earnings_yield for book_to_market", "Blend two value measures"],
  },
  {
    id: "value-quality",
    name: "Quality at a reasonable price",
    family: "Fundamentals",
    level: 3,
    idea: "Cheap and profitable. Cheap alone can mean a bad business; profitable alone can mean you overpay. Together they cover each other's weakness.",
    expression: "rank(earnings_yield) + rank(roe)",
    tweaks: ["Weight value more: 2 * rank(earnings_yield) + rank(roe)", "Add -leverage as a third ingredient"],
  },
  {
    id: "value-reversal",
    name: "Value plus reversal",
    family: "Fundamentals",
    level: 3,
    idea: "A slow signal (value) plus a fast one (weekly reversal). They rely on unrelated effects, so the blend is steadier than either alone.",
    expression: "rank(earnings_yield) + rank(-ts_delta(close, 5))",
    tweaks: ["Weight them unequally", "Try book_to_market instead of earnings_yield"],
  },
  // ── Blends ──────────────────────────────────────────────────────────────────
  {
    id: "blend-rev-pv",
    name: "Reversal plus price-volume",
    family: "Blends",
    level: 3,
    idea: "Add two different ideas together (each ranked first) and remove the sector effect. Blends are how real alphas are usually built.",
    expression: "group_neutralize(rank(-ts_delta(close, 5)) + rank(-ts_corr(close, volume, 10)), sector)",
    tweaks: ["Weight one idea more: 2 * rank(…) + rank(…)", "Add a third idea"],
  },
  {
    id: "blend-rev-lowvol",
    name: "Reversal plus low volatility",
    family: "Blends",
    level: 2,
    idea: "Weekly reversal plus the low-volatility effect. Two ideas that don't depend on each other.",
    expression: "rank(-ts_delta(close, 5)) + rank(-ts_std(returns, 20))",
    tweaks: ["Weight the signals unequally", "Swap the volatility window"],
  },
  {
    id: "blend-agree",
    name: "Act only when both agree",
    family: "Blends",
    level: 3,
    idea: "Multiply two ranked signals instead of adding them. The product is large only when both agree, so you trade less but with more conviction.",
    expression: "rank(-ts_delta(close, 5)) * rank(-ts_std(returns, 20))",
    tweaks: ["Compare with the same two signals added", "Try a different second signal"],
  },
];
